Feature branch
Guy-Gustave/the-next-web pull request #1
Opened 2020-06-13 19:33 UTC by Guy-Gustave

![screen 1](https://user-images.githubusercontent.com/56753805/84577534-639ed800-adbd-11ea-819b-6a1b7f3c9652.png)
this is the navbar and 1st article

2020-06-13 22:15 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @Guy-Gustave!👋 
You have done a wonderful job with your project so far! It looks really good! 👏 👏   There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

### Navigation Bar

- **Large Version**

- [ ] The text in the yellow banner should be left-aligned, not centered. Please compare your clone with the original page and fix this.
The original page 👇 
![Screen Shot 2020-06-13 at 11 09 49 PM](https://user-images.githubusercontent.com/48804258/84579061-0c9fff80-adcb-11ea-8bfb-004a276a3237.png)
Your clone 👇 
![Screen Shot 2020-06-13 at 11 09 56 PM](https://user-images.githubusercontent.com/48804258/84579062-0d389600-adcb-11ea-9d4f-aa4234e4a56e.png)

- **Medium Version**

- [ ] The TNW logo should appear at the leftmost part of the navigation bar in the medium screen size. Please check my screenshots below and fix this.
Your clone 👇 
![Screen Shot 2020-06-13 at 11 13 34 PM](https://user-images.githubusercontent.com/48804258/84579269-c350af80-adcc-11ea-8c47-085d33dbb3d6.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 13 24 PM](https://user-images.githubusercontent.com/48804258/84579270-c3e94600-adcc-11ea-9290-a2ab8b763fa2.png)

### Top 3 articles section

- **Large version**

- [ ] the gap between the large article on the left and the two smaller articles on the right is larger than it should be. There should also be a gap between the two articles on the right. Please compare your clone with the original page in the screenshots below and fix this. 
The original page 👇 
![Screen Shot 2020-06-13 at 11 25 35 PM](https://user-images.githubusercontent.com/48804258/84579344-322e0880-adcd-11ea-88ca-5ff3746f6a2e.png)
Your clone 👇 
![Screen Shot 2020-06-13 at 11 25 25 PM](https://user-images.githubusercontent.com/48804258/84579348-39551680-adcd-11ea-9dcb-64d895e1b847.png)

- [ ] Additionally, the date, time, and author name are not positioned correctly on the articles. Please compare your clone with the original page in the screenshots above and fix this. ☝️ 

-  **Medium Version**

- [ ] The TNW logo in the large article on the left should disappear on the medium screen. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-13 at 11 30 02 PM](https://user-images.githubusercontent.com/48804258/84579413-d0ba6980-adcd-11ea-936d-6c1f619221b8.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 29 49 PM](https://user-images.githubusercontent.com/48804258/84579416-d6b04a80-adcd-11ea-871c-3b849a534d96.png)

- **Small Version**

- [ ] The first article is partially hidden by the navigation bar. Please fix this. 
Your clone 👇 
![Screen Shot 2020-06-13 at 11 31 48 PM](https://user-images.githubusercontent.com/48804258/84579444-10815100-adce-11ea-818b-e6176c3e8a47.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 32 09 PM](https://user-images.githubusercontent.com/48804258/84579451-1b3be600-adce-11ea-9a06-61887635f54a.png)

- [ ] The date, time, author name, and article titles are not properly positioned on the articles on the small screen. Please compare it with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-13 at 11 33 28 PM](https://user-images.githubusercontent.com/48804258/84579472-4aeaee00-adce-11ea-82be-5a3662d8558f.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 33 39 PM](https://user-images.githubusercontent.com/48804258/84579473-51796580-adce-11ea-99a7-cc00afec9baf.png)
### Latest News Section

- **Medium Version**

- [ ] This section should align to 3 news articles per row in the medium screen. Please see the screenshots below and fix this.
Your clone 👇 
![Screen Shot 2020-06-13 at 11 45 06 PM](https://user-images.githubusercontent.com/48804258/84579660-eaf54700-adcf-11ea-89e2-476719e19421.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 45 40 PM](https://user-images.githubusercontent.com/48804258/84579667-ff394400-adcf-11ea-8033-bb8b2a9bf64a.png)

### Latest Funding section
- **Large version**

- [ ] The links (add info, get updates by email, see more) should be in line with the latest funding heading. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-13 at 11 48 57 PM](https://user-images.githubusercontent.com/48804258/84579712-74a51480-add0-11ea-9dbc-b514cb3901e5.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 49 19 PM](https://user-images.githubusercontent.com/48804258/84579716-81296d00-add0-11ea-9926-fe83464bf80d.png)
 

- **Medium Version**

- [ ] This section should align to 3 articles per row in the medium screen size. Please see the screenshots below.
The original page 👇 
![Screen Shot 2020-06-13 at 11 51 22 PM](https://user-images.githubusercontent.com/48804258/84579741-cb125300-add0-11ea-97d9-4f93d14a3ada.png)
Your clone 👇 
![Screen Shot 2020-06-13 at 11 51 41 PM](https://user-images.githubusercontent.com/48804258/84579747-d796ab80-add0-11ea-820b-2e2ae6308577.png)

### Categories (Apps, Gear, Tech, etc) section
- **Large version**

- [ ] The third element of the first row is not aligned properly with the other elements in the row. Please compare your clone with the original page and fix this. 
The original page 👇 
![Screen Shot 2020-06-13 at 11 54 16 PM](https://user-images.githubusercontent.com/48804258/84579774-32300780-add1-11ea-8325-05ca22114550.png)
Your clone 👇 
![Screen Shot 2020-06-13 at 11 54 04 PM](https://user-images.githubusercontent.com/48804258/84579780-3825e880-add1-11ea-97dd-a57aac464f3f.png)



- **Medium Version**

- [ ] This section should align to 2 category boxes per row in the medium screen size. Please compare your clone with the original page in the screenshots below. 
The original page 👇 
![Screen Shot 2020-06-13 at 11 56 34 PM](https://user-images.githubusercontent.com/48804258/84579826-876c1900-add1-11ea-96be-0a0bdf8da98e.png)
Your clone 👇 
![Screen Shot 2020-06-13 at 11 57 45 PM](https://user-images.githubusercontent.com/48804258/84579841-aff41300-add1-11ea-8e2c-a9f640721e45.png)

 ### Latest Deals Section
- **Large version**

- [ ] The "see all deals" link should be aligned to the right, not centered. 
Your clone 👇 
![Screen Shot 2020-06-13 at 11 59 14 PM](https://user-images.githubusercontent.com/48804258/84579862-e467cf00-add1-11ea-9bf1-ab1fb1a62441.png)
The original page 👇 
![Screen Shot 2020-06-13 at 11 59 42 PM](https://user-images.githubusercontent.com/48804258/84579865-f3e71800-add1-11ea-9ec7-76edd0971e94.png)



- **Medium Version**

- [ ] This section should align to 3 deals per row in the medium screen size. Please compare your clone with the original page in the screenshots below. 
The original page 👇 
![Screen Shot 2020-06-14 at 12 01 13 AM](https://user-images.githubusercontent.com/48804258/84579888-2bee5b00-add2-11ea-8634-6376fd639b6e.png)
Your clone 👇 
![Screen Shot 2020-06-14 at 12 01 31 AM](https://user-images.githubusercontent.com/48804258/84579896-3577c300-add2-11ea-939f-d3cb5d2ce130.png)



- **Small Version**

- [ ] The "Latest Deals" title and the "see all deals link" should not wrap to the next line on the small screen. Additionally, this section is taking up too much space on the small screen. 
Your clone 👇 
![Screen Shot 2020-06-14 at 12 03 15 AM](https://user-images.githubusercontent.com/48804258/84579942-956e6980-add2-11ea-8577-38fe314839c6.png)

![Screen Shot 2020-06-14 at 12 03 19 AM](https://user-images.githubusercontent.com/48804258/84579929-75d74100-add2-11ea-9f5a-2bb94a8baf67.png)
The original page 👇 
![Screen Shot 2020-06-14 at 12 04 52 AM](https://user-images.githubusercontent.com/48804258/84579950-ad45ed80-add2-11ea-9644-5f9f4e23d913.png)

### Overall

- [ ] I’m not seeing any linter checks in your project. Please ensure stickler is enabled in your repo and all the files were copied correctly. 
![Screen Shot 2020-06-13 at 11 02 19 PM](https://user-images.githubusercontent.com/48804258/84578944-01989f80-adca-11ea-882a-914504d68c37.png)

- [ ] It’s bet [...]

2020-06-13 22:15 UTC, BrittanyBlake commented on css/style.css
> +} */
Please remove commented code

2020-06-13 22:15 UTC, BrittanyBlake commented on css/style.css
> +} */
Please remove commented code

2020-06-13 22:16 UTC, BrittanyBlake commented on css/style.css
> +  /* z-index: 1; */
Please remove commented code

2020-06-13 22:16 UTC, BrittanyBlake commented on css/style.css
> +} */
Please remove commented code

2020-06-13 22:16 UTC, BrittanyBlake commented on css/style.css
> +    } */
Please remove commented code

2020-06-14 19:29 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Hello @Guy-Gustave 🖐.

### Nice job implementing the changes 👏.

However, there are still some changes required before we can move forward.

- There are some stickler errors that still need fixing. Please pay attention to that.

- The `article-1 vid` class' height should be increased to match the original.

  Right now 👇

  ![image](https://user-images.githubusercontent.com/57726348/84601705-e9934f80-ae9f-11ea-83f5-ec347cbdd9c4.png).

  Original 👇  
  
  ![image](https://user-images.githubusercontent.com/57726348/84601717-fe6fe300-ae9f-11ea-86ad-616dcb1bf71c.png)

- The `latest news` section must have some space on either side and there should be four cards in a row.

  Right now 👇

  ![image](https://user-images.githubusercontent.com/57726348/84601750-1fd0cf00-aea0-11ea-82be-ad0cc6e4f692.png)

  Original 👇  

  ![image](https://user-images.githubusercontent.com/57726348/84601736-18112a80-aea0-11ea-946b-a1c082e853c1.png)

- The `lates funding rounds` section should have some space on either side. The `red-img` class is not showing.

   Right now 👇

  ![image](https://user-images.githubusercontent.com/57726348/84601814-8d7cfb00-aea0-11ea-94d5-aa8fab9140d2.png)

  Original 👇  

  ![image](https://user-images.githubusercontent.com/57726348/84601810-8524c000-aea0-11ea-8cf2-17a74e31c60f.png)

- The `app-gear` section should have some space on either side.

  Right now 👇 
  
  ![image](https://user-images.githubusercontent.com/57726348/84601905-3c213b80-aea1-11ea-835f-119b944d7669.png)

  Original 👇  

  ![image](https://user-images.githubusercontent.com/57726348/84601913-4a6f5780-aea1-11ea-8403-c74a50e59b01.png)

- The `latest deals` section must have some space on either side and there should be four cards in a row.

  Right now 👇

  ![image](https://user-images.githubusercontent.com/57726348/84601932-6b37ad00-aea1-11ea-98c2-33bd960e0033.png)

  Original 👇  

  ![image](https://user-images.githubusercontent.com/57726348/84601926-6246db80-aea1-11ea-8f32-09bacf1b6d82.png)

- The `bottom-context` text should be in one line.

  Right now 👇

  ![image](https://user-images.githubusercontent.com/57726348/84601959-a6d27700-aea1-11ea-895e-5b5d89c496a9.png)

  Original 👇  

  ![image](https://user-images.githubusercontent.com/57726348/84601955-9fab6900-aea1-11ea-852f-2eaea28630eb.png)

- Your site is not responsive. In medium and small screens all of the elements are overflowing on the x-axis and the fonts in the top 3 articles section are larger than it should be.
  
  ![image](https://user-images.githubusercontent.com/57726348/84602061-61fb1000-aea2-11ea-89c4-83df3c12e57a.png)

  ![image](https://user-images.githubusercontent.com/57726348/84602067-6e7f6880-aea2-11ea-8982-ee1f7ec82331.png)
  
  ![image](https://user-images.githubusercontent.com/57726348/84602081-8a830a00-aea2-11ea-9692-c964ff4e0463.png)

The main objective of this project is to understand media queries in CSS. I see that you have only used one breakpoint, where 2 breakpoints were needed.

![image](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png)

### Focus on how the styles are changing in the original website for each breakpoint and try to emulate that.

Apply the suggested changes and request another code review.

Happy coding 👨‍💻

2020-06-15 06:50 UTC, Guy-Gustave commented
i hope i have checked all suggested. and thank you. now it is seen on mobile and large screen, well displaying

2020-06-15 07:31 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle:  :stop_sign: 
A great project so far :clap:  You have done such impressive work :clap:  However there are a few issues that have prevented me from approving the project please fix the following issue before resubmitting. :arrow_down: 

- [ ] There are still stickler issues in your project. You have to fix all errors before your project can be approved kindly fix all the errors :arrow_down: 
![linter errors](https://user-images.githubusercontent.com/32361963/84628903-212ae780-aef2-11ea-978c-991d5278412a.jpg)

- [ ] There are some responsiveness issues in your project. Remember, You have to make your project extremely responsive. Kindly fix all the responsiveness issues. :arrow_down: 

![responsivness issue](https://user-images.githubusercontent.com/32361963/84629145-81218e00-aef2-11ea-92e2-f14afa79618b.jpg)

- [ ] If you want to hide some items on your mobile view kindly don't just change the color to white,   instead use `display: none` in your CSS :arrow_down: 
![medium_view](https://user-images.githubusercontent.com/32361963/84629345-d3fb4580-aef2-11ea-9137-031db9ff00d5.jpg)

Also, I noticed there are a few issues you haven't addressed as advised by the previous TSE. Kindly take a step back and address all the issues as advised. It is a requirement before your project can be approved :smiley: 

If you have any question concerning the review kindly reach me on slack using this **@peterrobert**

### Happy coding  :computer:

2020-06-15 13:07 UTC, Guy-Gustave commented
i made all suggested correction and remove all stickler errors
![article1](https://user-images.githubusercontent.com/56753805/84660944-e046c900-af19-11ea-8ca7-61b05b2c7f7b.png)

2020-06-15 13:17 UTC, santiago-rodrig commented
# PR under review by @santiago-rodrig (TSE)

2020-06-15 13:27 UTC, Guy-Gustave commented
hello rodrig, i hope you are saying the footer. but on my original page is
like this. i may align on one line but the original was like that. thank
you. and the grid that they told me that they must have  spaces i already
changed. thank you

On Mon, Jun 15, 2020 at 3:17 PM Santiago Rodriguez <notifications@github.com>
wrote:

> PR under review by @santiago-rodrig <https://github.com/santiago-rodrig>
> (TSE)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Guy-Gustave/the-next-web/pull/1#issuecomment-644129093>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANQ75DKRPBKJ5DJMO2XF54TRWYNPHANCNFSM4N5DUTVQ>
> .
>

2020-06-15 13:40 UTC, santiago-dev96 requested changes
# Changes required :wrench:

Good job so far! But there are still some things to do.

1. Your navigation bar is not being displayed the same way that it is displayed on the original page

**Original - Small Screens**

<img width="426" alt="Screen Shot 2020-06-15 at 9 22 14 AM" src="https://user-images.githubusercontent.com/43162770/84663016-98f51400-aeea-11ea-9049-6073fbdf5290.png">

**Original - Medium Screens**

<img width="773" alt="Screen Shot 2020-06-15 at 9 23 02 AM" src="https://user-images.githubusercontent.com/43162770/84663189-cfcb2a00-aeea-11ea-815c-d236f2b4eed0.png">

**Yours - Small Screens**

<img width="427" alt="Screen Shot 2020-06-15 at 9 22 22 AM" src="https://user-images.githubusercontent.com/43162770/84663228-dce81900-aeea-11ea-85f0-07852c3b99dc.png">

**Yours - Medium Screens**

<img width="768" alt="Screen Shot 2020-06-15 at 9 23 10 AM" src="https://user-images.githubusercontent.com/43162770/84663272-ebcecb80-aeea-11ea-9a12-be5c4a1fb5a0.png">

2. Your **Latest News** section is not being displayed as it is displayed on the original page

**Original - Small Screens**

<img width="470" alt="Screen Shot 2020-06-15 at 9 26 32 AM" src="https://user-images.githubusercontent.com/43162770/84663768-98a94880-aeeb-11ea-9048-1ca482e0b745.png">

**Original - Medium Screens**

<img width="749" alt="Screen Shot 2020-06-15 at 9 26 07 AM" src="https://user-images.githubusercontent.com/43162770/84663818-ac54af00-aeeb-11ea-89cf-51c847828896.png">

**Yours - Small Screens**

![latest_small](https://user-images.githubusercontent.com/43162770/84663885-c2626f80-aeeb-11ea-80fd-c58db50704b4.gif)

**Yours - Medium Screens**

<img width="683" alt="Screen Shot 2020-06-15 at 9 25 48 AM" src="https://user-images.githubusercontent.com/43162770/84663947-d27a4f00-aeeb-11ea-8bd1-7f3c4aed5ea9.png">

Please submit another CRR after implementing the required changes, and please, take the time to review your project carefully, and also don't forget to review the page that you are trying to clone thoroughly.

You can find me in slack as **srodrig**, happy coding! :wave:

2020-06-15 13:47 UTC, Guy-Gustave commented
thank you. let me focus on it i see medium have problem you're right

On Mon, Jun 15, 2020 at 3:40 PM Santiago Rodriguez <notifications@github.com>
wrote:

> *@santiago-rodrig* requested changes on this pull request.
> Changes required 🔧
>
> Good job so far! But there are still some things to do.
>
>    1. Your navigation bar is not being displayed the same way that it is
>    displayed on the original page
>
> *Original - Small Screens*
>
> [image: Screen Shot 2020-06-15 at 9 22 14 AM]
> <https://user-images.githubusercontent.com/43162770/84663016-98f51400-aeea-11ea-9049-6073fbdf5290.png>
>
> *Original - Medium Screens*
>
> [image: Screen Shot 2020-06-15 at 9 23 02 AM]
> <https://user-images.githubusercontent.com/43162770/84663189-cfcb2a00-aeea-11ea-815c-d236f2b4eed0.png>
>
> *Yours - Small Screens*
>
> [image: Screen Shot 2020-06-15 at 9 22 22 AM]
> <https://user-images.githubusercontent.com/43162770/84663228-dce81900-aeea-11ea-85f0-07852c3b99dc.png>
>
> *Yours - Medium Screens*
>
> [image: Screen Shot 2020-06-15 at 9 23 10 AM]
> <https://user-images.githubusercontent.com/43162770/84663272-ebcecb80-aeea-11ea-9a12-be5c4a1fb5a0.png>
>
>    1. Your *Latest News* section is not being displayed as it is
>    displayed on the original page
>
> *Original - Small Screens*
>
> [image: Screen Shot 2020-06-15 at 9 26 32 AM]
> <https://user-images.githubusercontent.com/43162770/84663768-98a94880-aeeb-11ea-9048-1ca482e0b745.png>
>
> *Original - Medium Screens*
>
> [image: Screen Shot 2020-06-15 at 9 26 07 AM]
> <https://user-images.githubusercontent.com/43162770/84663818-ac54af00-aeeb-11ea-89cf-51c847828896.png>
>
> *Yours - Small Screens*
>
> [image: latest_small]
> <https://user-images.githubusercontent.com/43162770/84663885-c2626f80-aeeb-11ea-80fd-c58db50704b4.gif>
>
> *Yours - Medium Screens*
>
> [image: Screen Shot 2020-06-15 at 9 25 48 AM]
> <https://user-images.githubusercontent.com/43162770/84663947-d27a4f00-aeeb-11ea-8bd1-7f3c4aed5ea9.png>
>
> Please submit another CRR after implementing the required changes, and
> please, take the time to review your project carefully, and also don't
> forget to review the page that you are trying to clone thoroughly.
>
> You can find me in slack as *srodrig*, happy coding! 👋
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Guy-Gustave/the-next-web/pull/1#pullrequestreview-430653142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANQ75DPP3D2PQO7Q6DF67STRWYQEPANCNFSM4N5DUTVQ>
> .
>

2020-06-15 23:58 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello @Guy-Gustave   👋 
You are doing a great job with this project so far! 💪 Great job applying the feedback you have received from myself and the other TSEs. 🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] There are still some stickler issues that need to be resolved. Please fix these.
![Screen Shot 2020-06-16 at 1 33 46 AM](https://user-images.githubusercontent.com/48804258/84716167-ace45880-af72-11ea-893d-52c8e4c74b0d.png)

- [ ] The Latest Funding should be vertically aligned with the Latest News section above it. This was pointed out by a previous TSE who asked you to add space on either sides. 
The original page 👇 
![Screen Shot 2020-06-16 at 1 43 48 AM](https://user-images.githubusercontent.com/48804258/84716234-d4d3bc00-af72-11ea-89ab-b6da9c3e782d.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 1 45 36 AM](https://user-images.githubusercontent.com/48804258/84716329-15cbd080-af73-11ea-97d0-11717eb4ea80.png)

- [ ] In the Apps, Gear, Tech, etc. section, the article images are not properly aligned with the red banner below them. This is an issue with all of the article categories. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-16 at 1 49 00 AM](https://user-images.githubusercontent.com/48804258/84716496-8e329180-af73-11ea-89bb-fbbcfad1aa29.png)
The original page 👇 
![Screen Shot 2020-06-16 at 1 49 50 AM](https://user-images.githubusercontent.com/48804258/84716540-ac988d00-af73-11ea-9431-3a4269043039.png)

- [ ] Your clone is still not responsive on the medium and small screens. This was pointed out on all prior reviews. 
Your clone- Medium screen 👇 
![Screen Shot 2020-06-16 at 1 54 46 AM](https://user-images.githubusercontent.com/48804258/84716827-82939a80-af74-11ea-942b-39b72ff205ac.png)
Your clone- Small screen 👇 
![Screen Shot 2020-06-16 at 1 55 21 AM](https://user-images.githubusercontent.com/48804258/84716831-832c3100-af74-11ea-9d58-bcd0d741c9b6.png)

- There is way too much white space when scrolling to the right of your clone on the medium and small screens.

- [ ] Please review all previous TSE comments and ensure that you have done all the required changes. 



 



****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-16 06:59 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Nice job making the changes 🎉🙌, but we still need to work on some issues.

- The `app-img align` and `latest-bottom` divs must be aligned, as pointed out by the previous TSE.
- The `latest news`, `latest funding`, `apps, gear, tech` and `latest deals` sections must have some space on either side so that they are in the center of the screen, as I had pointed out earlier.

  ![image](https://user-images.githubusercontent.com/57726348/84601750-1fd0cf00-aea0-11ea-82be-ad0cc6e4f692.png)

  ![image](https://user-images.githubusercontent.com/57726348/84601814-8d7cfb00-aea0-11ea-94d5-aa8fab9140d2.png)

  ![image](https://user-images.githubusercontent.com/57726348/84601905-3c213b80-aea1-11ea-835f-119b944d7669.png)

  ![image](https://user-images.githubusercontent.com/57726348/84601932-6b37ad00-aea1-11ea-98c2-33bd960e0033.png)

- Your clone is not yet responsive. The elements are shrinking when the screen is resized, whereas, it should adapt to the screen size and change its styles by using media queries.

### Medium screen

![image](https://user-images.githubusercontent.com/57726348/84740845-bd74ed00-afcb-11ea-97e0-089f74ba0902.png)

### Small screen

![image](https://user-images.githubusercontent.com/57726348/84740893-d2518080-afcb-11ea-8416-2b07941600c1.png)

I really appreciate your not-giving-up mentality. In order to move ahead you need to make sure that you understand how media queries work. This is the objective of this project. Let's make sure to take a step back, go through all of the reviews (including this one) and understand what has been asked of you. Do make sure that you also understand how the original site is structured. I can guarantee you, once you understand how styles change when the same is accessed from different screen sizes, life would be so much easier.

### Take your time to understand the media queries. once you are done, make the changes and submit another code review.

Happy coding 👨‍💻

2020-06-16 09:16 UTC, Guy-Gustave commented
thank you for the review. i hope i made suggested changes. thank you. can you review again?

2020-06-16 12:41 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @Guy-Gustave  :wave:
-
You have done a good job leading to this point! Kindly note that while it might be prudent to try and keep up with our partners or at times our set goals, a lot of caution should be taken especially when working on projects that demand much of our attention such as these. A positive thing to note is that the project is coming along quite well, given the applied guidelines pointed by our awesome TSEs :tada: And for that, keep it up.

We, however, do have some few changes to carry out before we proceed (see review comment).
##
The [clone](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html) shows a good understanding and usage of building with responsive design. 💯 We, however, do need to ensure nothing is messed up. Kindly compare the differences between the clone and the source page, and carry out the necessary suggestions below. 👇  

## Large Screen

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html)|
|:---:|:---:|
|![source](https://user-images.githubusercontent.com/22345961/84770042-8f99a380-afdf-11ea-9bc1-01f5b52f06fb.png)|![clone](https://user-images.githubusercontent.com/22345961/84770055-958f8480-afdf-11ea-99f3-b3c9a3f8502d.png)|

### NavBar
- The main header contents in the main navbar(white) and the underneath(yellow), should be aligned to the far left of their respective navbars. Right now, they appear to be centrally aligned which should not be the case. Also, in the main navbar still, please ensure the contents to the right are aligned to the far-right as compared to how they are positioned right now. Kindly fix this.
### Three Articles
- Increase the height and width of the website's logo to match its original source.
-  Reorder the positioning of the date in the third article of the top three articles (move it to the bottom of the article's headline).
- Reposition the date of the main article (move it to the far right of its container element). Currently, it is centrally positioned which is not the case when compared to the source page.
- Increase the font of the header of the main article to match the source page.
### Middle Section
- Reduce the view width size of the `latest news`, `latest funding`,  `apps, gears, tech etc `, and `latest deals` section to match those of the source page's width.

### Footer
- The Footer also appears to be in need of some changes. Compare the differences below 👇 and work on the suggested changes.

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html)|
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/84771683-82ca7f00-afe2-11ea-9a2b-0fdc81a24610.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/84771696-878f3300-afe2-11ea-8977-fbd927f61310.png)|

- When we compare the two, there seems to be different from one another. The goal here is to make them strikingly similar. 
- Ensure the social icons are centrally well placed in their respective container elements, and that their padding is evenly distributed (not touching their container's borders). Take care of the colours as well.
- The `EVENTS`, `ABOUT`, `ADVERTISE`, `JOBS`, and `CONTACT` should all be well spaced out. Take care of the spelling mistakes as well.
- The bottom-most footer elements should be aligned in a single line.

## Medium Screen
### Navbar
- Take note of the colour topography of the main navbar(white). It is currently greyish in colour instead of white. Take care of the overflow of the wordings as well during the screen breakpoint transition from large to medium.

### Latest funding

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html)|
|:---:|:---:|
|![latest-funding-medium](https://user-images.githubusercontent.com/22345961/84773385-fff6f380-afe4-11ea-8495-c16cc09810ec.png)|![latest-funding-medium-clone](https://user-images.githubusercontent.com/22345961/84773393-05ecd480-afe5-11ea-9620-89bb2128b04a.png)|

- The latest funding section only displays three articles on the medium screen display. Kindly, let's find a way of hiding the fourth one in case of our clone page.

### Footer
- Attention is also drawn to the footer of both small and medium screens. Kindly take note of the two and work on the differences below. 👇 

|[Source Page](https://thenextweb.com/) |[Clone page](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html)|
|:---:|:---:|
|![footer-medium-small](https://user-images.githubusercontent.com/22345961/84773952-d094b680-afe5-11ea-918c-ac00ba0c3314.png)|![footer-medium-small-clone](https://user-images.githubusercontent.com/22345961/84773966-d5f20100-afe5-11ea-851f-660da8f73baa.png)|

## Small Screen 
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Guy-Gustave/the-next-web/feature-branch/index.html)|
|:---:|:---:|
|![small-screen](https://user-images.githubusercontent.com/22345961/84774410-75af8f00-afe6-11ea-9fde-1c124035c99f.png)|![small-screen-clone](https://user-images.githubusercontent.com/22345961/84774424-7b0cd980-afe6-11ea-8119-bd1506009703.png)|

- Increase the general height of the top three articles to match those of the source page in the small screens.

## Stylesheets 
- Please make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright). We do have a repeated styling rule here: https://github.com/Guy-Gustave/the-next-web/blob/f815a08ad637cf06698c33db9aea8839097b3c88/css/style.css#L340

#### OPTIONAL:
 - Validate your stylesheet using this [tool](https://jigsaw.w3.org/css-validator/validator)

## README
- Improve the screenshots in the README.
- Make the README look more professional by hiding the live link inside of placeholders to look neater.
##
- If you have any questions concerning the changes, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-16 15:51 UTC, Guy-Gustave commented
hey Christian i hope i made almost changes, except the footer because it was like mine. when i start it was like now after i changed and now it seems like before because i changed from Saturday. another change is the latest funding, it was 4 items before. i hope the aim oh the project is now. thank you

2020-06-16 18:54 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-16 19:01 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**@Guy-Gustave** 
Good job with the improvements in the appearance on your page :muscle:  
Your page meets most of the requirements :clap: :clap: :clap:  
 There is just a detail to improve in your CSS before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).

### OPTIONAL
- [ ] Use header tag for the content on the top of your page. Also, footer tag should be after main tag, not inside.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras
(for any question you can contact me in slack as @oscarporras02)

2020-06-16 19:01 UTC, andresporras3423 commented on css/style.css
> +}
Don't repeat yourself, in order to minimize code you can group selectors with the same style definition.

2020-06-16 19:01 UTC, andresporras3423 commented on css/style.css
> +}
Same styles of selector from line 15. In order to minimize code you can group selectors with the same style definition

2020-06-16 20:18 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## It's all coming together now. You have come a long way. Just a little more to go.

- The `latest funding` section needs to be exactly like the original.
### Clone
![image](https://user-images.githubusercontent.com/57726348/84821794-4ece7880-b039-11ea-88de-a73f198dcf7e.png)

### Original
![image](https://user-images.githubusercontent.com/57726348/84821837-6279df00-b039-11ea-9325-00823051a9cd.png)

- This image is coming over the navbar in the mobile view 👇
![Annotation 2020-06-17 013840](https://user-images.githubusercontent.com/57726348/84823084-64dd3880-b03b-11ea-89fd-046e6ac745fe.jpg)

- The top image in `apps, gear, tech,...` section is shrinking when resized 👇
![Annotation 2020-06-17 014031](https://user-images.githubusercontent.com/57726348/84823256-ae2d8800-b03b-11ea-9da5-b19420ea66cb.jpg)

Original 👇
![Annotation 2020-06-17 014049](https://user-images.githubusercontent.com/57726348/84823289-ba194a00-b03b-11ea-889e-f8a345991448.jpg)

- At width - 420px (and below), the whole clone (except for the navbar) starts shrinking 👇

![Annotation 2020-06-17 014521](https://user-images.githubusercontent.com/57726348/84823610-43c91780-b03c-11ea-9d7f-fb84a220cf64.jpg)

- In your `style.css`  file, there is an invalid property -> `padding: auto;` at line 581. The invalid style is for the `.vid` class. Fix that.

Make sure to work on these changes before requesting for code review.

Happy coding 👨‍💻

2020-06-16 21:41 UTC, Guy-Gustave commented
i finish all suggested. thank you

2020-06-17 00:15 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-17 00:28 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @Guy-Gustave** 
Nice job implementing the requirements of the last review :clap: :clap: :clap:
There are some improvements to do:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).
- [ ]  Correct the next problems in your page which appears in the small screen size version of your page:

![](https://i.imgur.com/WP5zEsml.png)

Compare this with the original page:

![](https://i.imgur.com/LxjATuVl.png)

Correct also this problem which appears in the medium screen size version of your page:

![](https://i.imgur.com/wzZiIsvl.png)

Now, in the footer, the link must appear in the same line in the large screen size version. Look your footer:

![](https://i.imgur.com/fKeFGv4l.png)

And the footer of the original page:

![](https://i.imgur.com/LyDNXLEl.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-17 00:28 UTC, andresporras3423 commented on css/style.css
> +}
Same styles of the selector as line 103. In order to minimize code, you can group selectors with the same style definition.

2020-06-17 00:28 UTC, andresporras3423 commented on css/style.css
> +}
Same styles of the selector as the line 274. In order to minimize code, you can group selectors with the same style definition.

2020-06-17 00:28 UTC, andresporras3423 commented on css/style.css
> +}
Don't repeat yourself. In order to minimize code, you can group selectors with the same style definition.

2020-06-17 05:14 UTC, Guy-Gustave commented
i hope now everything is okay. even the footer i change

2020-06-17 06:40 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :mechanic: 
**hello** @Guy-Gustave :wave: 
Great job implementing the suggestions from the previous review. :muscle:  :clap:  You have done a great job so far :+1:  However there are still some changes that are required in order for us to approve this project. 

- [ ] Kindly you didn't fix the issue on the footer as advised by the previous TSE. You need to improve on that. :smile:   Remember your site should look like the clone.
![footer](https://user-images.githubusercontent.com/32361963/84863476-a7276980-b07d-11ea-8f06-1bcae5c14818.jpg)

- [ ] Kindly also fix the overflow issue. One of your icons is falling off the container during the mobile view
![off the container](https://user-images.githubusercontent.com/32361963/84863596-d342ea80-b07d-11ea-8fde-2728caaa6c92.jpg)
 **Remember the main reason for this project is to make sure you learn about responsive design** :smile: 

- [ ] Also on your mobile view there is an overflow on the X-axis. You can fix this by referencing the body tag and hiding the over-flow on the x-axis `overflow-x: hidden`

**kindly improve on those and submit your project for another review**

### HAPPY CODING :muscle:

2020-06-17 06:57 UTC, Guy-Gustave commented
I don't know how it happens again I had fixed before. but check again it's okay now

2020-06-17 07:13 UTC, peterrobert approved these changes
### APPROVED :+1:  :fireworks: :1st_place_medal: 
**HELLO** :wave: 
The project now looks great to me. You have done such a good job of fixing all the errors. Am sure you have learned a lot

### ON TO THE NEXT PROJECT
### HAPPY CODING

2020-06-17 07:25 UTC, merged